### ISSUE TITLE
How to choose platformio env?

### ISSUE THREAD

**Issue by nopeslide** [ShilaTu/esp32-core#15]
I see several options

- branch based
  - add a release/debug specific branch which sets the corresponding default env
  - this means we have to manage multiple branches
- Makefile based
  - add a Makefile variable to specify the env, which defaults to something
  - yet another makefile state, which may not be obvious, but easy to use (see `make dev`)
- directory based
  - multiple platformio ini files
  - choose the directory and go

**Comment by ikstream** [comment]
I would prefer the Makefile based, as we discussed earlier. 
Either as a variable or as an additional target. Will you add it to #12 or should this be handled separately  from the pr?

**Comment by nopeslide** [comment]
@ikstream This should be handled in a different PR.

**Comment by ikstream** [comment]
Addressed in #29
